spring:
#  spring.redis.host=localhost
#  spring.redis.port=6379
  # redis:
  #   host: ${SPRING_REDIS_HOST} # localhost
  #   port: 6379
  config:
    import: ${SPRING_CONFIG_IMPORT} # optional:configserver:http://localhost:50000  # test
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # user