
#   To Gating the Product Service configuration file from the config server
#--------------------------------------------------------------------------------------------------

spring:
  config:
    import: ${SPRING_CONFIG_IMPORT} # optional:configserver:http://config-server:50000 # optional:configserver:http://localhost:5000
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # product
  openai:
    api-key: ${OPENAI_API_KEY} # before start or deploying set the environment variable OPENAI_API_KEY
    client:
      properties:
        model: gpt-5-nano # or your preferred model
        temperature: 0.7
        max-tokens: 150
        top-p: 1.0

#To Gating the Product Service configuration file from local file
#--------------------------------------------------------------------------------------------------

## Eqipped product Service
#server:
#  port: 5004
#
## Eureka start
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
## Spring Start
#spring:
#  application:
#    name: PRODUCT-SERVICE
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#    mongodb:
#      uri: mongodb://admin:admin123@localhost:27017/labequiped?authSource=admin
#      database: labequiped





